x-backend-defaults: &backend-defaults
  image: '${CUSTOM_IMAGE:-frappe/erpnext}:${CUSTOM_TAG:-${ERPNEXT_VERSION}}'
  restart: '${RESTART_POLICY:-unless-stopped}'
  volumes:
    - sites:/home/frappe/frappe-bench/sites
    - apps:/home/frappe/frappe-bench/apps
  platform: linux/amd64
  depends_on:
    configurator:
      condition: service_completed_successfully

services:
  db:
    image: mariadb:10.6
    restart: unless-stopped
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: '%'
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "--password=${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis-cache:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis-cache-data:/data

  redis-queue:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis-queue-data:/data

  configurator:
    image: '${CUSTOM_IMAGE:-frappe/erpnext}:${CUSTOM_TAG:-${ERPNEXT_VERSION}}'
    restart: on-failure
    platform: linux/amd64
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - apps:/home/frappe/frappe-bench/apps
    entrypoint: [bash, -c]
    command:
      - >
        if [ ! -d "apps/hrms" ]; then
          bench get-app hrms --branch version-15;
        fi;
        ./env/bin/pip install -e apps/hrms;
        ls -1 apps > sites/apps.txt;
        bench set-config -g db_host $$DB_HOST;
        bench set-config -gp db_port $$DB_PORT;
        bench set-config -g redis_cache "redis://$$REDIS_CACHE";
        bench set-config -g redis_queue "redis://$$REDIS_QUEUE";
        bench set-config -g redis_socketio "redis://$$REDIS_QUEUE";
        bench set-config -gp socketio_port $$SOCKETIO_PORT;
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      SOCKETIO_PORT: "9000"
    depends_on:
      db:
        condition: service_healthy

  backend:
    <<: *backend-defaults
    entrypoint: [bash, -c]
    command:
      - >
        ./env/bin/pip install -e apps/hrms;
        gunicorn -b 0.0.0.0:8000 -w $$GUNICORN_WORKERS --threads $$GUNICORN_THREADS -t $$GUNICORN_TIMEOUT frappe.app:application
    environment:
      GUNICORN_WORKERS: '${GUNICORN_WORKERS:-2}'
      GUNICORN_THREADS: '${GUNICORN_THREADS:-4}'
      GUNICORN_TIMEOUT: '${GUNICORN_TIMEOUT:-120}'

  websocket:
    <<: *backend-defaults
    command: [node, /home/frappe/frappe-bench/apps/frappe/socketio.js]

  queue-short:
    <<: *backend-defaults
    entrypoint: [bash, -c]
    command:
      - >
        ./env/bin/pip install -e apps/hrms;
        bench worker --queue short,default

  queue-long:
    <<: *backend-defaults
    entrypoint: [bash, -c]
    command:
      - >
        ./env/bin/pip install -e apps/hrms;
        bench worker --queue long,default,short

  scheduler:
    <<: *backend-defaults
    entrypoint: [bash, -c]
    command:
      - >
        ./env/bin/pip install -e apps/hrms;
        bench schedule

  frontend:
    image: '${CUSTOM_IMAGE:-frappe/erpnext}:${CUSTOM_TAG:-${ERPNEXT_VERSION}}'
    restart: unless-stopped
    platform: linux/amd64
    command: [nginx-entrypoint.sh]
    environment:
      BACKEND: backend:8000
      SOCKETIO: websocket:9000
      FRAPPE_SITE_NAME_HEADER: '${FRAPPE_SITE_NAME_HEADER:-$$host}'
      UPSTREAM_REAL_IP_ADDRESS: '127.0.0.1'
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: 'off'
      PROXY_READ_TIMEOUT: '${PROXY_READ_TIMEOUT:-120}'
      CLIENT_MAX_BODY_SIZE: '${CLIENT_MAX_BODY_SIZE:-50m}'
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    depends_on:
      - backend
      - websocket
    ports:
      - "8181:8080"

volumes:
  db-data:
  redis-cache-data:
  redis-queue-data:
  sites:
  apps:
